# Generated by Django 4.2.6 on 2023-12-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Empno', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=100)),
                ('Job', models.CharField(max_length=100)),
                ('Sal', models.PositiveIntegerField()),
                ('MGR', models.PositiveIntegerField()),
                ('Hiredate', models.DateField()),
                ('Comm', models.PositiveIntegerField()),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
