# Generated by Django 4.2.6 on 2023-12-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('bId', models.IntegerField(primary_key=True, serialize=False)),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalGrade',
            fields=[
                ('grade', models.IntegerField(primary_key=True, serialize=False)),
                ('losal', models.IntegerField()),
                ('highsal', models.IntegerField()),
            ],
        ),
    ]
